SELECT * FROM CCCONSTANTES


-- Esta consulta encuentra todas las tablas que tienen una columna llamada NOMBRE
SELECT table_name 
FROM USER_TAB_COLUMNS 
WHERE column_name = 'NOMBRE'
ORDER BY table_name;





-- Consulta para encontrar tablas que tienen algún registro con NOMBRE = 'TODOS'
-- Reemplaza estas tablas con las que encontraste en la consulta anterior

SELECT 'ASEGURADO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM ASEGURADO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'BENEFICIARIO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM BENEFICIARIO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CALENDARIO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CALENDARIO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCACTIVIDADGIRO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCACTIVIDADGIRO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCBANCO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCBANCO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCCOBERTURAS' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCCOBERTURAS
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCCOLORES' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCCOLORES
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCCOLS' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCCOLS
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCCOMANDOS' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCCOMANDOS
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCCONSTANTES' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCCONSTANTES
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCCPCOLONIAS' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCCPCOLONIAS
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCDETALLEMENU' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCDETALLEMENU
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCESTADO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCESTADO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCESTATUSPOLIZA' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCESTATUSPOLIZA
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCESTATUSRECIBO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCESTATUSRECIBO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCESTATUSUSUARIO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCESTATUSUSUARIO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCGENERO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCGENERO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCGIRO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCGIRO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCGRUPOS' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCGRUPOS
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCINSTRUMENTOSPAGO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCINSTRUMENTOSPAGO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCJUSTIFICACIONCANCELACION' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCJUSTIFICACIONCANCELACION
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCMARCA' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCMARCA
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCMENU' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCMENU
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCMODULO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCMODULO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCMONEDA' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCMONEDA
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCMUNICIPIO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCMUNICIPIO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCNACIONALIDAD' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCNACIONALIDAD
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCNOMBRESCATALOGO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCNOMBRESCATALOGO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCOCUPACION' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCOCUPACION
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCOPERACIONESPOLIZA' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCOPERACIONESPOLIZA
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCOPERADOR' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCOPERADOR
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCPAIS' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCPAIS
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCPAISNACIMIENTO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCPAISNACIMIENTO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCPARAMETROS' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCPARAMETROS
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCPARENTESCO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCPARENTESCO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCPERFIL' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCPERFIL
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCPLANES' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCPLANES
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCPLAZOSPAGO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCPLAZOSPAGO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCPROFESION' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCPROFESION
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCSERVICIO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCSERVICIO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCSEXO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCSEXO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCSUBMENU' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCSUBMENU
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCTIPOCAMPO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCTIPOCAMPO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCTIPOCOTIZADOR' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCTIPOCOTIZADOR
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCTIPOIDENTIFICACION' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCTIPOIDENTIFICACION
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCTIPOPLANTILLA' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCTIPOPLANTILLA
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCTIPOVEHICULO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCTIPOVEHICULO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCTIPOVENTA' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCTIPOVENTA
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCTIPOVISTA' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCTIPOVISTA
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCUSO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCUSO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CCZONA' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CCZONA
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CONFIGURACIONFORMULARIO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CONFIGURACIONFORMULARIO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'CONFIGURACIONMENSAJESNOTIFICACION' AS TABLA, COUNT(*) AS CANTIDAD
    FROM CONFIGURACIONMENSAJESNOTIFICACION
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'DATOSAGENTEPLANTILLA' AS TABLA, COUNT(*) AS CANTIDAD
    FROM DATOSAGENTEPLANTILLA
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'DOCUMENTO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM DOCUMENTO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'EMPLEADO' AS TABLA, COUNT(*) AS CANTIDAD
    FROM EMPLEADO
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'EMPLEADOAUX' AS TABLA, COUNT(*) AS CANTIDAD
    FROM EMPLEADOAUX
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'IMAGENESPLANTILLA' AS TABLA, COUNT(*) AS CANTIDAD
    FROM IMAGENESPLANTILLA
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'INSTITUCIONES' AS TABLA, COUNT(*) AS CANTIDAD
    FROM INSTITUCIONES
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'PARAMETROS' AS TABLA, COUNT(*) AS CANTIDAD
    FROM PARAMETROS
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'USUARIOS' AS TABLA, COUNT(*) AS CANTIDAD
    FROM USUARIOS
 WHERE NOMBRE = 'TODOS'
UNION ALL
SELECT 'VARIABLESUNICAS' AS TABLA, COUNT(*) AS CANTIDAD
    FROM VARIABLESUNICAS
 WHERE NOMBRE = 'TODOS'

ORDER BY CANTIDAD DESC;




-- Consulta para mostrar los registros con NOMBRE = 'TODOS' en CCPLAZOSPAGO
SELECT 
    *  -- Selecciona todas las columnas, puedes ajustar para columnas específicas
FROM 
    CCPLAZOSPAGO
WHERE 
    NOMBRE = 'TODOS';