UPDATE COTIZACION SET ESTATUSFIRMA = 'Approved' WHERE FOLIO = 'w9jasc76uyz7od642wlbotmy1qbif56d';

SELECT * FROM POLIZA WHERE NUMEROPOLIZA = '370000167601'

SELECT * FROM COTIZACION WHERE FOLIO = '0h5x5b3z899loiyfjzmqhiost1mbehil'

SELECT * FROM CCCONSTANTES


SELECT
    /* ID,
    FECHAREGISTRO, */
    NOMBRE,
   /*  DESCRIPCION,
    ESACTIVO, */
    RUTA
FROM
    CCCONSTANTES
WHERE
    NOMBRE = 'uso';



/* Tomando la data de dos tablas. */
SELECT
    P.NOMBREINSTANCIA,
    CM.*
FROM
    CONFIGURACIONMULTIAGENTES CM
JOIN
    PLANTILLA P ON CM.PLANTILLA_ID = P.ID
WHERE
    CM.PLANTILLA_ID = 2;

/* Borrar todos los registros de la instancia de ANUALIZADA */
DELETE FROM CONFIGURACIONMULTIAGENTES 
WHERE PLANTILLA_ID = 2;

SELECT
    *
FROM CCTIPOCOTIZADOR
    
SELECT * FROM CCNOMBRESCATALOGO


INSERT INTO CCNOMBRESCATALOGO (NOMBRE, NOMBRECOMPONENTE, ESACTIVO)
VALUES ('REGIMEN FISCAL', 'c-select-regimen-fiscal', 1);


