SELECT
    ID,
    NOMBRE,
    TIPODOCUMENTO,
    JSONDATADOC
FROM
    DOCUMENTO
WHERE
    COTIZACION_ID = '32164';


    UPDATE COTIZACION SET ESTATUSFIRMA = 'Approved' WHERE FOLIO = 'ou16pss05oj48k72c8nxr6lc4q4mychi';
    UPDATE COTIZACION SET ESTATUSFIRMA = 'Approved' WHERE FOLIO = 'ou16pss05oj48k72c8nxr6lc4q4mychi';
